/*
 * Copyright (c) 2025 BekenCorp. All rights reserved.
 * 
 * This software is proprietary and confidential. No part of this software may be
 * reproduced, distributed, or transmitted in any form or by any means, including
 * photocopying, recording, or other electronic or mechanical methods, without the
 * prior written permission of BekenCorp, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted
 * by copyright law.
 * 
 * For permission requests, write to BekenCorp at armino_support@bekencorp.com.

 * Author: Beken LVGL Designer Tool
*/
/**
 * @file event_runtime.c
 * @brief Event Runtime Support Implementation
 * 
 * This file contains the implementation of event runtime support functions.
 * Generated by Beken LVGL Designer Tool.
 */

#include "event_runtime.h"
#include "beken_ui.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

/**
 * @brief Switch to a screen (with lazy initialization)
 * @param target Pointer to the page pointer in bk_lv_tool_ui structure (e.g., &bk_lv_tool_ui.page_2)
 * @param fademode Screen load animation mode (LV_SCR_LOAD_ANIM_NONE, LV_SCR_LOAD_ANIM_OVER_LEFT, etc.)
 * @param spd Animation speed in milliseconds
 * @param delay Animation delay in milliseconds
 * @param target_init Function pointer to initialize the target page if not already initialized
 */
void navigate_to_screen(lv_obj_t** target, lv_screen_load_anim_t anim_type, int anim_time, int delay, bool auto_del, void (*target_init)(bk_lv_ui_t*))
{
    if (target == NULL) {
        return;
    }
    
    if ((*target == NULL || !lv_obj_is_valid(*target)) && target_init != NULL) {
        target_init(&bk_lv_tool_ui);
    }
    
    if ((*target != NULL && lv_obj_is_valid(*target))) {
        lv_screen_load_anim(*target, anim_type, anim_time, delay, auto_del);
    }
}

/**
 * @brief Switch locale (language)
 * @param locale Target locale code (e.g., "en", "zh-CN")
 * @param reload_page Whether to reload the current page after switching locale
 */
void switch_locale(const char* locale, bool reload_page)
{
    // i18n is not enabled
    printf("Warning: i18n is not enabled, cannot switch language\n");
}
